# numpy indexing and slicing

## There are three types of indexing mwthod
### 1) field access
### 2) basic slicing
### 3) advanced indexing


## <font color="purple">Field access

In [3]:
import numpy as np
a=np.arange(5,15)
print(a)
#accessing of array element with index value
print(a[3]) #Field access by using index value

[ 5  6  7  8  9 10 11 12 13 14]
8


In [4]:
#Assigning element by using index value
a[0]=50
a

array([50,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# For multi Dimentional array

In [13]:
b=np.arange(1,10)
b=np.reshape(b,(3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## accessing element for 3D array

In [7]:
b[1,1] # accessing element of 1 indexed row and 1 indexed column of 3D array

5

In [9]:
b[2,2]

9

## assigning element to 3D array

In [14]:
b[1,2]=60
b

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 7,  8,  9]])

In [20]:
# access and assign elements of array
a=np.arange(11,20)
a=np.reshape(a,(3,3))
print(a)
print(a[1,1])
print(a[2,0])
print(a[2,2])
a[0,2]=130
a[2,1]=180
print(a)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
15
17
19
[[ 11  12 130]
 [ 14  15  16]
 [ 17 180  19]]


# Slicing of array

## <font color="purple"> 1D array

In [ ]:
a=np.arange(1,10)
a

### accessing element by slicing

In [23]:
print(a[2:7]) # accessing elements from index 2 to 7 of array

[3 4 5 6 7]


In [25]:
print(a[2:]) # accessing elements from index 2 to last index of array

[3 4 5 6 7 8 9]


In [27]:
print(a[-1])  # accessing last element of array

9


### assigning element by slicing

In [29]:
a[4:]=50 # assigning 4 index to last index element as 50
print(a)

[ 1  2  3  4 50 50 50 50 50]


## Multi-Dimentional array - Slicing

In [31]:
a=np.reshape(a,(3,3))
a

array([[ 1,  2,  3],
       [ 4, 50, 50],
       [50, 50, 50]])

In [33]:
# Assigning index 5 to last element as 10 then reshape it
a=np.arange(11,20)
a[5:]=10
a=np.reshape(a,(3,3))
a

array([[11, 12, 13],
       [14, 15, 10],
       [10, 10, 10]])

In [37]:
# reshape and then assignment is done
b=np.arange(11,20)
b=np.reshape(b,(3,3))
print("Before assignment:\n",b)
b[1][2]=10
b[2:]=10
print("After assignment:\n",b)

Before assignment:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
After assignment:
 [[11 12 13]
 [14 15 10]
 [10 10 10]]


# Ellipse :- accessing and assigning whole row and column elements.

In [45]:
b[...] # for accessing whole array using ellipse

array([[11, 12, 13],
       [14, 15, 10],
       [10, 10, 10]])

## For accessing the 0th row by ellipse

In [38]:
print(b[0,...])

[11 12 13]


In [40]:
print(b[1,...]) # 2nd row

[14 15 10]


## For accessing the 0th column by ellipse

In [41]:
print(b[...,0])

[11 14 10]


In [42]:
print(b[...,1])

[12 15 10]


## For assigning elements by ellipse

In [47]:
b[...]=10
b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [56]:
# accessing 1st index row and 1st column column of 3D array
c=np.arange(1,10)
c=np.reshape(c,(3,3))
print(c,"\n")
print("1st index row : \n",c[1,...],"\n")
print("1st index column : \n",c[...,1],"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

1st index row : 
 [4 5 6] 

1st index column : 
 [2 5 8] 



# Advanced Indexing :- Accessing elements of array by index array

In [58]:
a=np.arange(5,16)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
index=np.array([1,2,3])
a[index] # accessing elements of array by index array

array([6, 7, 8])

In [66]:
b=np.arange(15,26)
print(b)
index=np.array([2,5,9]) # accsssing 17 20 24 elements by thier index values
b[index]

[15 16 17 18 19 20 21 22 23 24 25]


array([17, 20, 24])

# Bool indexing

In [68]:
c=np.arange(10,100,5)
print(c)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [70]:
print(c>45) # if element satisfy condition then it represent True otherwise False

[False False False False False False False False  True  True  True  True
  True  True  True  True  True  True]


## <font color="blue"> make a two matrics of range 1-9(3,3) and 11-19(3,3) and do addition, subtraction, multiplication and division of matrix

In [76]:
a=np.arange(1,10)
a=np.reshape(a,(3,3))
b=np.arange(11,20)
b=np.reshape(b,(3,3))
print("a = \n",a,"\n")
print("b = \n",b,"\n")
print("Addition of a and b : \n",a+b,"\n")
print("Subtraction of a and b : \n",a-b,"\n")
print("Multiplication of a and b : \n",a*b,"\n")
print("Division of a and b : \n",a/b,"\n")

a = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

Addition of a and b : 
 [[12 14 16]
 [18 20 22]
 [24 26 28]] 

Subtraction of a and b : 
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]] 

Multiplication of a and b : 
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

Division of a and b : 
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]] 

