In [1]:
import numpy as np

In [2]:
#unsigned integer
c=np.array([1,2,3],dtype=np.uint16)
print(c)
print(c.dtype)

[1 2 3]
uint16


In [3]:
a=np.ones((3,3),dtype="int32")
print(a)
c=np.float32(a) # copy and typecasting
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
