# pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
print(pd.__version__)

1.5.3


# Series :- Series store the value in single column with index value

In [4]:
# generate random values in column
s=pd.Series(np.random.randn(5))
print(s)

0    0.300198
1    1.220883
2   -0.385629
3    0.255277
4   -0.658934
dtype: float64


In [5]:
s=pd.Series(np.random.randn(5), index=['A','B','C','D','E']) # changing the index type
print(s)

A    0.470151
B    0.022194
C   -0.216041
D    1.258691
E    0.130258
dtype: float64


# DataFrame : DataFrame store the value in multiple columns and multiple rows with index value

In [19]:
# generate random values in column and rows
df=pd.DataFrame(np.random.rand(5,5),columns=list('abcde')) # Define columns name
print(df)

          a         b         c         d         e
0  0.557054  0.787230  0.165556  0.102619  0.129527
1  0.945438  0.802866  0.435945  0.896647  0.752869
2  0.656465  0.493414  0.381586  0.721984  0.908231
3  0.742408  0.169475  0.448908  0.772797  0.826409
4  0.521508  0.802913  0.648845  0.842108  0.246467


In [20]:
# generate random values in column and rows
df=pd.DataFrame(np.random.rand(5,5),columns=list('abcde'),index=[1,2,3,4,5]) # Define columns name and index
print(df)

          a         b         c         d         e
1  0.829278  0.661047  0.421975  0.917056  0.680129
2  0.891914  0.416853  0.458463  0.133045  0.256521
3  0.476225  0.896960  0.338663  0.257655  0.885434
4  0.211804  0.963909  0.358730  0.370168  0.202924
5  0.244246  0.440207  0.767787  0.960620  0.553629


In [23]:
array=np.random.rand(4,5)
print(array)
df=pd.DataFrame(array) # DataFrame take array as input 
print(df)

[[0.92448079 0.38525646 0.79763665 0.50641868 0.64934861]
 [0.65107475 0.98033017 0.26110179 0.57210419 0.70424482]
 [0.67971167 0.30251003 0.29354332 0.49804463 0.33002173]
 [0.04911664 0.33726732 0.59090363 0.88208824 0.5615115 ]]
          0         1         2         3         4
0  0.924481  0.385256  0.797637  0.506419  0.649349
1  0.651075  0.980330  0.261102  0.572104  0.704245
2  0.679712  0.302510  0.293543  0.498045  0.330022
3  0.049117  0.337267  0.590904  0.882088  0.561512


# <font color=red> Reading .csv files

In [26]:
w=pd.read_csv("weather.csv")
w

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## info() :-  information command for table data

In [27]:
w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          6 non-null      object
 1   temperature  6 non-null      int64 
 2   windspeed    6 non-null      int64 
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [29]:
w1=pd.read_csv("weather1.csv")
w1

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [30]:
w1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          9 non-null      object 
 1   temperature  5 non-null      float64
 2   windspeed    5 non-null      float64
 3   event        7 non-null      object 
dtypes: float64(2), object(2)
memory usage: 416.0+ bytes


## shape :- It return no. of rows and columns of table data

In [33]:
w1.shape #return (no. of rows, no. of columns)

(9, 4)

In [34]:
w.shape

(6, 4)

## Slicing :- returning a specific rows and columns of table

In [39]:
w1[2:6] # return from 2 to 6-1 rows

day  temperature  windspeed  event
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain
5  1/8/2017          NaN        NaN  Sunny

In [42]:
w1[['day','event']] # return a specific cloumns by its name from table

day   event
0   1/1/2017    Rain
1   1/4/2017   Sunny
2   1/5/2017    Snow
3   1/6/2017     NaN
4   1/7/2017    Rain
5   1/8/2017   Sunny
6   1/9/2017     NaN
7  1/10/2017  Cloudy
8  1/11/2017   Sunny

## describe() :- for checking the statistic values of the table data

In [43]:
w.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [44]:
w.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

### To check specific statistic value

In [45]:
w['temperature'].mean()

30.333333333333332

In [48]:
w['temperature'].std()

3.8297084310253524

# Displaying the value by condition

In [52]:
w[w.temperature>=30] # return the temperature value which is greater than or equal to 30

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## set_index() : it used to set index by any column of table

In [54]:
new_df=w.set_index('day') # return a table which have day as index column
new_df

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [55]:
w1=pd.read_csv("weather1.csv")
w1

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [56]:
w1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          9 non-null      object 
 1   temperature  5 non-null      float64
 2   windspeed    5 non-null      float64
 3   event        7 non-null      object 
dtypes: float64(2), object(2)
memory usage: 416.0+ bytes


# head() :- For reading top 5 element from above

In [57]:
w1.head()

day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

# tail() :- for reading 5 elememts from down

In [58]:
w1.tail()

day  temperature  windspeed   event
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

# isnull():- it return a table with True and False Values. false=no null, True=Null

In [63]:
w1.isnull()

day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False         True       True  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

# isnull().any() :- for checking the total null value from table data
## # return a column as True which has Null values otherwise true

In [64]:
w1.isnull().any() 

day            False
temperature     True
windspeed       True
event           True
dtype: bool

In [62]:
w1.isnull()

day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False         True       True  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

# isnull().sum() : - return the total no. of null values in each columns

In [65]:
w1.isnull().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

# isnull().sum().sum() :- return total no. of null values in whole table data

In [66]:
w1.isnull().sum().sum()

10

# dropna() : it drop(remove) row which has a null value

In [67]:
w1.dropna()

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

# fillna(0) :- it used to fill all null values with 0 of table data.

In [68]:
w1.fillna(0)

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        9.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017          0.0        0.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

# fillna({}) :- it is used to fill null valuas with specific value for specific columns

In [69]:
w1.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'not_event'
})

day  temperature  windspeed      event
0   1/1/2017         32.0        6.0       Rain
1   1/4/2017          0.0        9.0      Sunny
2   1/5/2017         28.0        0.0       Snow
3   1/6/2017          0.0        7.0  not_event
4   1/7/2017         32.0        0.0       Rain
5   1/8/2017          0.0        0.0      Sunny
6   1/9/2017          0.0        0.0  not_event
7  1/10/2017         34.0        8.0     Cloudy
8  1/11/2017         40.0       12.0      Sunny

## For fill null values with statistic values(min,max,mean...)

In [70]:
w1['temperature'].min()

28.0

In [ ]:
new_df=w1.fillna({
    w1.temperature:
})